export const ROLE_SYNONYMS: Record<string, string[]> = {
  // Software & Engineering
  software: [
    'software',
    'developer',
    'engineer',
    'engineering',
    'software developer',
    'software engineer',
    'swe',
    'sde',
    'programmer',
    'web',
    'application developer',
    'apps engineer',
    'application engineer',
    'solutions engineer',
    'systems engineer',
    'platform engineer',
    'principal engineer',
    'staff engineer',
    'senior software engineer',
    'junior software developer',
    'full stack engineer',
    'full stack developer',
    'backend developer',
    'frontend developer',
    'web developer',
    'web engineer',
    'api developer',
    'service engineer',
    'distributed systems',
    'microservices',
    'software architect',
    'solution architect',
    'software craftsmanship',
    'coder',
    'programmer analyst',
    'application programmer',
    'software specialist',
    'software consultant',
    'cloud software engineer',
    'saas engineer',
    'middleware developer',
    'integration developer',
    'site reliability',
    'sre',
    'dev engineer',
    'product engineer',
    'ML engineer',
    'data engineer',
    'QA engineer',
    'test engineer',
  ],
  backend: [
    'backend',
    'back end',
    'server',
    'api',
    'backend engineer',
    'backend developer',
    'microservices',
    'rest',
    'graphql',
    'node.js',
    'express',
    'koa',
    'spring',
    'spring boot',
    'java developer',
    'python developer',
    'django',
    'flask',
    'fastapi',
    'ruby on rails',
    'rails',
    'laravel',
    'php developer',
    'golang developer',
    'go developer',
    'c# developer',
    'dotnet developer',
    '.net developer',
    'postgresql',
    'mysql',
    'redis',
    'kafka',
    'rabbitmq',
    'message queue',
    'event-driven',
    'service mesh',
    'grpc',
    'orm',
    'database developer',
    'etl',
  ],
  frontend: [
    'frontend',
    'front end',
    'ui',
    'web',
    'frontend engineer',
    'frontend developer',
    'javascript',
    'typescript',
    'react',
    'vue',
    'angular',
    'svelte',
    'next.js',
    'nuxt',
    'vite',
    'webpack',
    'babel',
    'css',
    'scss',
    'less',
    'html',
    'ui engineer',
    'ui developer',
    'frontend architect',
    'web ui',
    'spa developer',
    'pwa',
    'storybook',
    'design systems',
    'accessibility',
    'a11y',
  ],
  'full stack': [
    'full stack',
    'fullstack',
    'full stack engineer',
    'full stack developer',
    'frontend',
    'backend',
    'mern',
    'mean',
    'lamp',
    'jamstack',
    'node.js',
    'react',
    'next.js',
    'graphql',
    'rest',
    'sql',
    'nosql',
    'postgres',
    'mysql',
    'mongodb',
    'firebase',
    'prisma',
    'typeorm',
    'django',
    'rails',
    'laravel',
    'ci/cd',
    'docker',
    'kubernetes',
    'cloud',
    'aws',
    'azure',
    'gcp',
    'devops',
    'testing',
    'e2e',
  ],
  mobile: [
    'mobile',
    'ios',
    'android',
    'react native',
    'flutter',
    'kotlin',
    'swift',
    'objective-c',
    'xcode',
    'android sdk',
    'jetpack compose',
    'swiftui',
    'gradle',
    'play store',
    'app store',
    'mobile engineer',
    'mobile developer',
    'mobile apps',
    'native mobile',
    'hybrid mobile',
    'capacitor',
    'cordova',
    'uiautomator',
    'espresso',
    'xcuitest',
    'mobile qa',
    'sdk developer',
  ],
  devops: [
    'devops',
    'site reliability engineer',
    'sre',
    'platform engineer',
    'infrastructure',
    'ci/cd',
    'kubernetes',
    'docker',
    'terraform',
    'pulumi',
    'ansible',
    'chef',
    'puppet',
    'helm',
    'istio',
    'linkerd',
    'prometheus',
    'grafana',
    'elk',
    'elasticsearch',
    'logstash',
    'kibana',
    'splunk',
    'observability',
    'monitoring',
    'on-call',
    'incident response',
    'capacity planning',
    'scalability',
    'reliability',
    'performance',
    'resilience',
  ],
  cloud: [
    'cloud',
    'aws',
    'azure',
    'gcp',
    'google cloud',
    'cloud engineer',
    'cloud architect',
    'cloud ops',
    'cloud sre',
    'serverless',
    'lambda',
    'cloudformation',
    'cdk',
    'ecs',
    'eks',
    'ecr',
    's3',
    'iam',
    'vpc',
    'route 53',
    'gke',
    'cloud run',
    'cloud functions',
    'app engine',
    'azure devops',
    'aks',
    'cosmos db',
    'azure functions',
    'cloud security',
    'cloud governance',
  ],
  data: [
    'data',
    'data engineer',
    'data scientist',
    'data analyst',
    'analytics',
    'etl',
    'ml',
    'machine learning',
    'ai',
    'artificial intelligence',
    'nlp',
    'deep learning',
    'mle',
    'analytics engineer',
    'bi',
    'business intelligence',
    'data analytics',
    'data warehouse',
    'data lake',
    'data platform',
    'big data',
    'spark',
    'hadoop',
    'kafka',
    'dbt',
    'snowflake',
    'redshift',
    'bigquery',
    'airflow',
    'prefect',
    'tableau',
    'power bi',
    'feature engineering',
    'model ops',
    'mlops',
    'data ops',
  ],
  qa: ['qa', 'quality assurance', 'test', 'testing', 'sdet', 'automation'],
  // Expand QA as separate key for richer matches
  quality: [
    'qa',
    'quality',
    'quality assurance',
    'test',
    'testing',
    'sdet',
    'automation',
    'test automation',
    'automation engineer',
    'manual tester',
    'qa engineer',
    'test engineer',
    'qa analyst',
    'test analyst',
    'qa lead',
    'qa manager',
    'quality engineer',
    'verification engineer',
    'validation engineer',
    'performance testing',
    'load testing',
    'security testing',
    'integration testing',
    'unit testing',
    'e2e testing',
    'regression testing',
    'test plans',
    'test cases',
    'bug triage',
    'bug tracking',
    'qa automation',
    'selenium',
    'cypress',
    'playwright',
    'appium',
    'jmeter',
    'postman',
    'api testing',
    'bdd',
    'tdd',
  ],
  design: [
    'designer',
    'product designer',
    'ux',
    'ui',
    'ux/ui',
    'interaction designer',
    'visual designer',
    'ux researcher',
    'design researcher',
    'service designer',
    'experience designer',
    'interface designer',
    'brand designer',
    'motion designer',
    'design technologist',
    'prototype',
    'prototyping',
    'wireframes',
    'user research',
    'usability',
    'accessibility',
    'design systems',
    'ux writer',
    'content designer',
    'visual design',
    'hci',
    'human-centered design',
    'figma',
    'sketch',
    'xd',
  ],
  product: ['product manager', 'pm', 'product management', 'product owner'],
  // Broader product management synonyms
  pm: [
    'product manager',
    'group product manager',
    'senior product manager',
    'associate product manager',
    'apm',
    'principal product manager',
    'product director',
    'head of product',
    'vp of product',
    'product owner',
    'product operations',
    'product ops',
    'technical product manager',
    'tpmm',
    'growth product manager',
    'platform product manager',
    'ai product manager',
    'ml product manager',
    'product strategist',
    'product analyst',
    'product lead',
    'product leadership',
    'roadmap',
    'product discovery',
    'product delivery',
    'agile product',
    'backlog',
    'prioritization',
    'stakeholder management',
    'product lifecycle',
    'plm',
  ],
  project: [
    'project manager',
    'project management',
    'project coordinator',
    'delivery manager',
    'scrum master',
    'agile project manager',
    'technical project manager',
    'it project manager',
    'program manager',
    'project lead',
    'pmo',
    'project management office',
    'engagement manager',
    'program director',
    'project director',
    'implementation manager',
    'delivery lead',
    'portfolio manager',
    'change manager',
    'project scheduler',
    'project planner',
    'project analyst',
    'project coordinator',
    'scrum of scrums',
    'agile coach',
    'kanban',
    'lean project',
    'prince2',
    'pmp',
    'stakeholder management',
    'risk management',
    'project governance',
    'raids',
    'status reporting',
    'project charter',
  ],
  sales: [
    'sales',
    'account executive',
    'ae',
    'sales manager',
    'business development',
    'bd',
    'bdr',
    'sdr',
    'sales development',
    'sales development representative',
    'business development representative',
    'inside sales',
    'field sales',
    'outside sales',
    'enterprise sales',
    'account manager',
    'strategic accounts',
    'mid-market sales',
    'channel sales',
    'alliances',
    'partnerships',
    'solutions consultant',
    'solutions engineer',
    'sales engineer',
    'pre-sales',
    'presales',
    'post-sales',
    'customer success',
    'renewals',
    'expansion',
    'quota carrying',
    'pipeline',
  ],
  marketing: [
    'marketing',
    'growth',
    'demand generation',
    'content',
    'seo',
    'sem',
    'social media',
    'performance marketing',
    'product marketing',
    'brand marketing',
    'digital marketing',
    'email marketing',
    'marketing automation',
    'marketo',
    'hubspot',
    'crm marketing',
    'lifecycle marketing',
    'paid media',
    'ppc',
    'adwords',
    'facebook ads',
    'tiktok ads',
    'influencer marketing',
    'pr',
    'public relations',
    'communications',
    'community',
    'content strategist',
    'copywriter',
    'marketing analytics',
    'campaign manager',
  ],
  support: [
    'support',
    'customer support',
    'customer success',
    'technical support',
    'help desk',
    'client support',
    'support engineer',
    'support specialist',
    'support analyst',
    'support technician',
    'solutions support',
    'customer care',
    'call center',
    'service desk',
    'it support',
    'desktop support',
    'field support',
    'incident management',
    'ticketing',
    'zendesk',
    'freshdesk',
  ],
  finance: [
    'finance',
    'financial analyst',
    'accountant',
    'controller',
    'cpa',
    'fp&a',
    'fp&a analyst',
    'financial planning',
    'treasury',
    'auditor',
    'audit',
    'tax accountant',
    'bookkeeper',
    'finance manager',
    'cfo',
    'accounts payable',
    'ap',
    'accounts receivable',
    'ar',
    'general ledger',
    'gl accountant',
    'financial reporting',
    'management reporting',
    'cost accounting',
    'financial controller',
  ],
  hr: [
    'hr',
    'human resources',
    'recruiter',
    'talent acquisition',
    'people ops',
    'people operations',
    'hr generalist',
    'hr manager',
    'hrbp',
    'human resources business partner',
    'compensation',
    'benefits',
    'total rewards',
    'recruiting coordinator',
    'technical recruiter',
    'sourcer',
    'talent partner',
    'employer branding',
    'learning and development',
    'l&d',
    'organizational development',
  ],
  ops: ['operations', 'ops', 'business operations', 'bizops'],
  operations: [
    'operations',
    'bizops',
    'business operations',
    'strategy and operations',
    'stratops',
    'revops',
    'revenue operations',
    'sales ops',
    'marketing ops',
    'cs ops',
    'process improvement',
    'continuous improvement',
    'lean',
    'six sigma',
    'okrs',
    'kpis',
    'business analyst',
    'operations analyst',
    'operations manager',
    'program operations',
    'go-to-market operations',
    'gtm operations',
    'strategic operations',
    'strategy',
    'execution',
    'planning',
    'resource planning',
    'capacity planning',
    'business planning',
    'forecasting',
    'workforce management',
    'vendor management',
  ],
  // Healthcare & Nursing
  nurse: [
    'nurse',
    'registered nurse',
    'rn',
    'r.n.',
    'staff nurse',
    'clinical nurse',
    'icu nurse',
    'er nurse',
    'emergency nurse',
    'surgical nurse',
    'pediatric nurse',
    'geriatrics nurse',
    'licensed practical nurse',
    'lpn',
    'registered practical nurse',
    'rpn',
    'nurse practitioner',
    'np',
    'aprn',
    'advanced practice nurse',
    'clinical nurse specialist',
    'cns',
    'charge nurse',
    'home health nurse',
    'public health nurse',
    'school nurse',
    'occupational health nurse',
    'psychiatric nurse',
    'mental health nurse',
    'oncology nurse',
    'dialysis nurse',
    'nephrology nurse',
    'cardiac nurse',
    'or nurse',
    'operating room nurse',
    'perioperative nurse',
    'med-surg nurse',
    'medical surgical nurse',
    'telemetry nurse',
    'float nurse',
    'travel nurse',
    'case manager nurse',
    'nurse educator',
    'nurse supervisor',
    'nurse manager',
    'wound care nurse',
    'hospice nurse',
  ],
  rn: ['rn', 'registered nurse', 'nurse'],
  lpn: ['lpn', 'licensed practical nurse', 'nurse'],
  rpn: ['rpn', 'registered practical nurse', 'nurse'],
};

export function expandTokens(baseTokens: string[]): string[] {
  const expanded = new Set<string>();
  for (const t of baseTokens) {
    const token = t.toLowerCase();
    expanded.add(token);
    for (const k of Object.keys(ROLE_SYNONYMS)) {
      if (token.includes(k)) {
        for (const s of ROLE_SYNONYMS[k]) expanded.add(s);
      }
    }
  }
  return Array.from(expanded);
}
